name: 'Build and push to container-registry.com'

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: build image and push
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buidlx
      uses: docker/setup-buildx-action@v3

    - name: Login to container-registry
      uses: docker/login-action@v3
      with: 
        registry: c8n.io
        username: ${{ secrets.C8N_USERNAME }}
        password: ${{ secrets.C8N_SECRET }}

      
    - name: Build and push container image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: c8n.io/indikaimk/my-flask-app:1.0.1

